### ISSUE TITLE
Finding breeding/feeding spots is currently not working

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [LasseBlaauwbroek/AlgorithmsForGeographicalData#1]
As far as I can see, this is because there is an access of the zeroth element of an empty array in the main file.

**Comment by danarouschop** [comment]
Fixed it. However, when I run the clustering when the loading of the gulls is not completed yet, then for some reason it doesn't finish at all (it gives no errors though..)

**Comment by LasseBlaauwbroek** [comment]
Cannot reproduce anymore (also not your comment Dana?)

**Comment by LasseBlaauwbroek** [comment]
Yes I can...

**Comment by danarouschop** [comment]
What error are you getting, and when..?

**Comment by LasseBlaauwbroek** [comment]
Done
