### ISSUE TITLE
Simplification not correct yet (the paths are broken up)

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [LasseBlaauwbroek/AlgorithmsForGeographicalData#5]

**Comment by ankurt44** [comment]
Simplification algorithm is correct. 
-There is something wrong with the values of epsilon that you calculate (it's very high, in lakhs!!!). I assume that the value of epsilon should be small (like 10kms or even smaller).
-Then something goes wrong when you draw 'polygons' for simplified trajectories and that is why the paths are broken.
Can you check on above two points and let me know.

PS. The simplification algorithm actually gave correct results on the map with the previous logic of drawing polygons on the map.

**Comment by danarouschop** [comment]
In the class tools the distances returned are in meters, the epsilon however is expressed in degrees. So there could be a conversion missing somewhere

**Comment by LasseBlaauwbroek** [comment]
Fixed. Working pretty well now. The only problem is when you zoom in on a hotspot with a lot of birds active.

It is also pretty slow to load the birds. Anything we can do to speed the simplification up Ankur?

**Comment by ankurt44** [comment]
To speed up simplifications, 
-sorting "epsilons" list
-get simplified trajectory for epsilon(0) using original trajectory
-for i>0 : get simplified trajectory for epsilon(i) using simplified trajectory of epsilon(i-1)
